# fly.toml app configuration file generated for markassafe on 2023-10-15T17:04:53-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "markassafe"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
